---
galaxy_info:
  author: Anand
  description: Installs Docker and runs container
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: EL
      versions:
        - 8
    - name: Amazon
      versions:
        - 2
dependencies: []
