apiVersion: v1
kind: Config
clusters:
- name: my-kube-playground  
- name: development
- name: production
contexts:
- name: my-kube-admin@my-kube-playground
- name: dev-user@development
- name: prod-user@production
users:
- name: my-kube-admin
- name: dev-user
- name: prod-user